begin;

-- BulkText Fresh 0.9 — Excel / CSV Import
-- Individual account import staging scoped to the hidden personal workspace.

create or replace function public.can_stage_contact_imports(p_organization_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.can_manage_org(p_organization_id);
$$;

create table if not exists public.contact_imports (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  uploaded_by uuid not null references public.profiles(id) on delete restrict,
  source_filename text not null check (char_length(source_filename) between 1 and 255),
  source_type text not null check (source_type in ('csv', 'xlsx')),
  source_size_bytes bigint not null check (source_size_bytes between 1 and 5242880),
  source_sha256 text not null check (source_sha256 ~ '^[0-9a-f]{64}$'),
  sheet_name text,
  headers jsonb not null check (jsonb_typeof(headers) = 'array'),
  column_mapping jsonb not null check (jsonb_typeof(column_mapping) = 'object'),
  total_rows integer not null check (total_rows between 1 and 5000),
  valid_phone_rows integer not null default 0 check (valid_phone_rows >= 0),
  invalid_phone_rows integer not null default 0 check (invalid_phone_rows >= 0),
  duplicate_phone_rows integer not null default 0 check (duplicate_phone_rows >= 0),
  status text not null default 'staged' check (status in ('staged')),
  created_at timestamptz not null default now()
);

create index if not exists contact_imports_org_created_idx
  on public.contact_imports (organization_id, created_at desc);

create index if not exists contact_imports_org_sha_idx
  on public.contact_imports (organization_id, source_sha256);

create table if not exists public.contact_import_rows (
  id bigint generated by default as identity primary key,
  import_id uuid not null references public.contact_imports(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  source_row_number integer not null check (source_row_number >= 2),
  raw_data jsonb not null check (jsonb_typeof(raw_data) = 'object'),
  raw_phone text not null default '',
  normalized_e164 text,
  phone_validation_status text not null check (phone_validation_status in (
    'valid', 'empty', 'invalid_characters', 'invalid_length', 'unsupported_country', 'unsupported_number_type'
  )),
  phone_validation_reason text not null,
  first_name text,
  last_name text,
  display_name text,
  custom_fields jsonb not null default '{}'::jsonb check (jsonb_typeof(custom_fields) = 'object'),
  duplicate_in_file boolean not null default false,
  created_at timestamptz not null default now(),
  unique (import_id, source_row_number),
  check (normalized_e164 is null or normalized_e164 ~ '^\+923[0-9]{9}$')
);

create index if not exists contact_import_rows_import_idx
  on public.contact_import_rows (import_id, source_row_number);

create index if not exists contact_import_rows_org_e164_idx
  on public.contact_import_rows (organization_id, normalized_e164)
  where normalized_e164 is not null;

alter table public.contact_imports enable row level security;
alter table public.contact_import_rows enable row level security;

create policy "contact_imports_select_members"
on public.contact_imports
for select
to authenticated
using (public.is_org_member(organization_id));

create policy "contact_import_rows_select_members"
on public.contact_import_rows
for select
to authenticated
using (public.is_org_member(organization_id));

create or replace function public.create_contact_import(
  p_organization_id uuid,
  p_source_filename text,
  p_source_type text,
  p_source_size_bytes bigint,
  p_source_sha256 text,
  p_sheet_name text,
  p_headers jsonb,
  p_column_mapping jsonb,
  p_rows jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_actor uuid := auth.uid();
  v_import_id uuid;
  v_filename text := trim(coalesce(p_source_filename, ''));
  v_sha text := lower(trim(coalesce(p_source_sha256, '')));
  v_row jsonb;
  v_raw_phone text;
  v_normalized_e164 text;
  v_validation_status text;
  v_validation_reason text;
  v_source_row_number integer;
  v_row_index integer := 0;
  v_valid integer := 0;
  v_invalid integer := 0;
  v_duplicates integer := 0;
  v_seen_e164 text[] := array[]::text[];
  v_duplicate boolean;
begin
  if v_actor is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if not public.can_stage_contact_imports(p_organization_id) then
    raise exception 'Personal workspace owner permission required to stage imports' using errcode = '42501';
  end if;

  if char_length(v_filename) < 1 or char_length(v_filename) > 255 then
    raise exception 'Source filename must be between 1 and 255 characters' using errcode = '22023';
  end if;

  if p_source_type not in ('csv', 'xlsx') then
    raise exception 'Source type must be csv or xlsx' using errcode = '22023';
  end if;

  if p_source_size_bytes is null or p_source_size_bytes < 1 or p_source_size_bytes > 5242880 then
    raise exception 'Import file size must be between 1 byte and 5 MB' using errcode = '22023';
  end if;

  if v_sha !~ '^[0-9a-f]{64}$' then
    raise exception 'Source SHA-256 fingerprint is required' using errcode = '22023';
  end if;

  if jsonb_typeof(p_headers) <> 'array' or jsonb_array_length(p_headers) < 1 or jsonb_array_length(p_headers) > 100 then
    raise exception 'Import headers must contain between 1 and 100 columns' using errcode = '22023';
  end if;

  if jsonb_typeof(p_column_mapping) <> 'object' or trim(coalesce(p_column_mapping->>'phone', '')) = '' then
    raise exception 'A phone column mapping is required' using errcode = '22023';
  end if;

  if not (p_headers @> jsonb_build_array(p_column_mapping->>'phone')) then
    raise exception 'Mapped phone column is not present in the import headers' using errcode = '22023';
  end if;

  if jsonb_typeof(p_rows) <> 'array' or jsonb_array_length(p_rows) < 1 or jsonb_array_length(p_rows) > 5000 then
    raise exception 'Import must contain between 1 and 5000 data rows' using errcode = '22023';
  end if;

  insert into public.contact_imports (
    organization_id, uploaded_by, source_filename, source_type, source_size_bytes,
    source_sha256, sheet_name, headers, column_mapping, total_rows
  ) values (
    p_organization_id, v_actor, v_filename, p_source_type, p_source_size_bytes,
    v_sha, nullif(trim(coalesce(p_sheet_name, '')), ''), p_headers, p_column_mapping, jsonb_array_length(p_rows)
  ) returning id into v_import_id;

  for v_row in select value from jsonb_array_elements(p_rows)
  loop
    v_row_index := v_row_index + 1;
    if jsonb_typeof(v_row) <> 'object' then
      raise exception 'Import row % must be a JSON object', v_row_index using errcode = '22023';
    end if;

    v_raw_phone := coalesce(v_row->>'rawPhone', '');
    select normalized_e164, validation_status, validation_reason
      into v_normalized_e164, v_validation_status, v_validation_reason
    from public.normalize_phone_number(v_raw_phone, 'PK')
    limit 1;

    if coalesce(v_row->>'sourceRowNumber', '') ~ '^[0-9]+$' then
      v_source_row_number := (v_row->>'sourceRowNumber')::integer;
    else
      v_source_row_number := v_row_index + 1;
    end if;

    if v_source_row_number < 2 then
      raise exception 'Import row number must be 2 or greater' using errcode = '22023';
    end if;

    v_duplicate := false;
    if v_validation_status = 'valid' and v_normalized_e164 is not null then
      v_valid := v_valid + 1;
      if v_normalized_e164 = any(v_seen_e164) then
        v_duplicate := true;
        v_duplicates := v_duplicates + 1;
      else
        v_seen_e164 := array_append(v_seen_e164, v_normalized_e164);
      end if;
    else
      v_invalid := v_invalid + 1;
    end if;

    insert into public.contact_import_rows (
      import_id, organization_id, source_row_number, raw_data, raw_phone,
      normalized_e164, phone_validation_status, phone_validation_reason,
      first_name, last_name, display_name, custom_fields, duplicate_in_file
    ) values (
      v_import_id,
      p_organization_id,
      v_source_row_number,
      coalesce(v_row->'rawData', '{}'::jsonb),
      v_raw_phone,
      v_normalized_e164,
      v_validation_status,
      v_validation_reason,
      nullif(trim(coalesce(v_row->>'firstName', '')), ''),
      nullif(trim(coalesce(v_row->>'lastName', '')), ''),
      nullif(trim(coalesce(v_row->>'displayName', '')), ''),
      coalesce(v_row->'customFields', '{}'::jsonb),
      v_duplicate
    );
  end loop;

  update public.contact_imports
  set valid_phone_rows = v_valid,
      invalid_phone_rows = v_invalid,
      duplicate_phone_rows = v_duplicates
  where id = v_import_id;

  insert into public.audit_logs (
    organization_id, actor_user_id, action, target_type, target_id, metadata
  ) values (
    p_organization_id,
    v_actor,
    'contacts.import_staged',
    'contact_import',
    v_import_id::text,
    jsonb_build_object(
      'filename', v_filename,
      'sourceType', p_source_type,
      'rows', jsonb_array_length(p_rows),
      'validPhoneRows', v_valid,
      'invalidPhoneRows', v_invalid,
      'duplicatePhoneRows', v_duplicates
    )
  );

  return v_import_id;
end;
$$;

create or replace function public.list_contact_imports(p_organization_id uuid)
returns table(
  import_id uuid,
  source_filename text,
  source_type text,
  source_size_bytes bigint,
  source_sha256 text,
  sheet_name text,
  total_rows integer,
  valid_phone_rows integer,
  invalid_phone_rows integer,
  duplicate_phone_rows integer,
  status text,
  created_at timestamptz,
  uploaded_by uuid
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if not public.is_org_member(p_organization_id) then
    raise exception 'Organization membership required' using errcode = '42501';
  end if;

  return query
  select
    i.id,
    i.source_filename,
    i.source_type,
    i.source_size_bytes,
    i.source_sha256,
    i.sheet_name,
    i.total_rows,
    i.valid_phone_rows,
    i.invalid_phone_rows,
    i.duplicate_phone_rows,
    i.status,
    i.created_at,
    i.uploaded_by
  from public.contact_imports i
  where i.organization_id = p_organization_id
  order by i.created_at desc, i.id desc
  limit 100;
end;
$$;

create or replace function public.delete_contact_import(
  p_organization_id uuid,
  p_import_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_filename text;
begin
  if v_actor is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if not public.can_stage_contact_imports(p_organization_id) then
    raise exception 'Personal workspace owner permission required to delete staged imports' using errcode = '42501';
  end if;

  select source_filename into v_filename
  from public.contact_imports
  where id = p_import_id and organization_id = p_organization_id;

  if v_filename is null then
    raise exception 'Import not found' using errcode = 'P0002';
  end if;

  delete from public.contact_imports
  where id = p_import_id and organization_id = p_organization_id;

  insert into public.audit_logs (
    organization_id, actor_user_id, action, target_type, target_id, metadata
  ) values (
    p_organization_id,
    v_actor,
    'contacts.import_deleted',
    'contact_import',
    p_import_id::text,
    jsonb_build_object('filename', v_filename)
  );
end;
$$;

revoke all on public.contact_imports from public, anon, authenticated;
revoke all on public.contact_import_rows from public, anon, authenticated;
grant select on public.contact_imports to authenticated;
grant select on public.contact_import_rows to authenticated;
grant all on public.contact_imports to service_role;
grant all on public.contact_import_rows to service_role;

revoke all on function public.can_stage_contact_imports(uuid) from public, anon;
revoke all on function public.create_contact_import(uuid, text, text, bigint, text, text, jsonb, jsonb, jsonb) from public, anon;
revoke all on function public.list_contact_imports(uuid) from public, anon;
revoke all on function public.delete_contact_import(uuid, uuid) from public, anon;

grant execute on function public.can_stage_contact_imports(uuid) to authenticated, service_role;
grant execute on function public.create_contact_import(uuid, text, text, bigint, text, text, jsonb, jsonb, jsonb) to authenticated, service_role;
grant execute on function public.list_contact_imports(uuid) to authenticated, service_role;
grant execute on function public.delete_contact_import(uuid, uuid) to authenticated, service_role;

update public.app_meta
set value = coalesce(value, '{}'::jsonb) || jsonb_build_object(
      'version', '0.9.0',
      'phase', 'excel_csv_import',
      'default_country', 'PK',
      'number_type', 'mobile',
      'normalization_version', 'pk-mobile-v1',
      'import_file_types', jsonb_build_array('csv', 'xlsx'),
      'max_import_rows', 5000,
      'max_import_file_bytes', 5242880
    ),
    updated_at = now()
where key = 'schema';

commit;
