begin;

-- BulkText Web 0.11.0 — Consent & Suppression
-- Adds append-only consent/suppression evidence and immutable recipient eligibility snapshots.
-- Campaign composition, confirmation and sending remain later gates.

create or replace function public.can_manage_contact_compliance(p_organization_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.org_role(p_organization_id) in ('owner', 'admin', 'campaign_manager'), false);
$$;

create or replace function public.can_lift_contact_suppressions(p_organization_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.org_role(p_organization_id) in ('owner', 'admin'), false);
$$;

create table if not exists public.contact_consent_events (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  normalized_e164 text not null check (normalized_e164 ~ '^\+923[0-9]{9}$'),
  event_type text not null check (event_type in ('granted', 'revoked')),
  source text not null check (source in ('web_form', 'paper_form', 'verbal', 'import', 'api', 'manual', 'other')),
  evidence_note text,
  evidence_reference text,
  occurred_at timestamptz not null,
  expires_at timestamptz,
  recorded_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  check (char_length(coalesce(evidence_note, '')) <= 1000),
  check (char_length(coalesce(evidence_reference, '')) <= 500),
  check (
    char_length(trim(coalesce(evidence_note, ''))) > 0
    or char_length(trim(coalesce(evidence_reference, ''))) > 0
  ),
  check (
    (event_type = 'granted' and (expires_at is null or expires_at > occurred_at))
    or (event_type = 'revoked' and expires_at is null)
  )
);

create index if not exists contact_consent_events_org_phone_idx
  on public.contact_consent_events (organization_id, normalized_e164, occurred_at desc, id desc);

create table if not exists public.contact_suppression_events (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  normalized_e164 text not null check (normalized_e164 ~ '^\+923[0-9]{9}$'),
  event_type text not null check (event_type in ('suppressed', 'lifted')),
  reason text check (reason in ('opt_out', 'complaint', 'manual', 'regulatory', 'other')),
  source text not null check (source in ('recipient_reply', 'import', 'api', 'manual', 'other')),
  note text,
  occurred_at timestamptz not null,
  recorded_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  check (char_length(coalesce(note, '')) <= 1000),
  check (
    (event_type = 'suppressed' and reason is not null)
    or (event_type = 'lifted' and reason is null and char_length(trim(coalesce(note, ''))) > 0)
  )
);

create index if not exists contact_suppression_events_org_phone_idx
  on public.contact_suppression_events (organization_id, normalized_e164, occurred_at desc, id desc);

alter table public.contact_consent_events enable row level security;
alter table public.contact_suppression_events enable row level security;

create policy "contact_consent_events_select_members"
on public.contact_consent_events
for select
to authenticated
using (public.is_org_member(organization_id));

create policy "contact_suppression_events_select_members"
on public.contact_suppression_events
for select
to authenticated
using (public.is_org_member(organization_id));

create or replace function public.contact_compliance_state_internal(
  p_organization_id uuid,
  p_normalized_e164 text
)
returns table(
  normalized_e164 text,
  consent_state text,
  consent_event_id bigint,
  consent_source text,
  consent_occurred_at timestamptz,
  consent_expires_at timestamptz,
  suppression_state text,
  suppression_event_id bigint,
  suppression_reason text,
  suppression_source text,
  suppression_occurred_at timestamptz,
  eligibility_state text,
  block_reason text
)
language sql
stable
security definer
set search_path = public
as $$
  with latest_consent as (
    select e.*
    from public.contact_consent_events e
    where e.organization_id = p_organization_id
      and e.normalized_e164 = p_normalized_e164
    order by e.occurred_at desc, e.id desc
    limit 1
  ), latest_suppression as (
    select e.*
    from public.contact_suppression_events e
    where e.organization_id = p_organization_id
      and e.normalized_e164 = p_normalized_e164
    order by e.occurred_at desc, e.id desc
    limit 1
  ), state as (
    select
      p_normalized_e164 as normalized_e164,
      case
        when c.id is null then 'none'
        when c.event_type = 'revoked' then 'revoked'
        when c.expires_at is not null and c.expires_at <= now() then 'expired'
        else 'granted'
      end as consent_state,
      c.id as consent_event_id,
      c.source as consent_source,
      c.occurred_at as consent_occurred_at,
      c.expires_at as consent_expires_at,
      case when s.event_type = 'suppressed' then 'suppressed' else 'clear' end as suppression_state,
      s.id as suppression_event_id,
      case when s.event_type = 'suppressed' then s.reason else null end as suppression_reason,
      s.source as suppression_source,
      s.occurred_at as suppression_occurred_at
    from (select 1) seed
    left join latest_consent c on true
    left join latest_suppression s on true
  )
  select
    st.normalized_e164,
    st.consent_state,
    st.consent_event_id,
    st.consent_source,
    st.consent_occurred_at,
    st.consent_expires_at,
    st.suppression_state,
    st.suppression_event_id,
    st.suppression_reason,
    st.suppression_source,
    st.suppression_occurred_at,
    case
      when st.suppression_state = 'suppressed' then 'blocked'
      when st.consent_state = 'granted' then 'eligible'
      else 'blocked'
    end as eligibility_state,
    case
      when st.suppression_state = 'suppressed' then 'suppressed'
      when st.consent_state = 'none' then 'no_consent'
      when st.consent_state = 'revoked' then 'consent_revoked'
      when st.consent_state = 'expired' then 'consent_expired'
      else null
    end as block_reason
  from state st;
$$;

create or replace function public.record_contact_consent(
  p_organization_id uuid,
  p_phone text,
  p_event_type text,
  p_source text,
  p_evidence_note text default null,
  p_evidence_reference text default null,
  p_occurred_at timestamptz default null,
  p_expires_at timestamptz default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_normalized text;
  v_status text;
  v_reason text;
  v_event_id bigint;
  v_occurred_at timestamptz := coalesce(p_occurred_at, now());
  v_note text := nullif(trim(coalesce(p_evidence_note, '')), '');
  v_reference text := nullif(trim(coalesce(p_evidence_reference, '')), '');
begin
  if v_actor is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if not public.can_manage_contact_compliance(p_organization_id) then
    raise exception 'Owner, Admin or Campaign Manager permission required to manage consent' using errcode = '42501';
  end if;

  if p_event_type is null or p_event_type not in ('granted', 'revoked') then
    raise exception 'Consent event type must be granted or revoked' using errcode = '22023';
  end if;

  if p_source is null or p_source not in ('web_form', 'paper_form', 'verbal', 'import', 'api', 'manual', 'other') then
    raise exception 'Unsupported consent source' using errcode = '22023';
  end if;

  if v_note is null and v_reference is null then
    raise exception 'Consent evidence note or reference is required' using errcode = '22023';
  end if;

  if char_length(coalesce(v_note, '')) > 1000 or char_length(coalesce(v_reference, '')) > 500 then
    raise exception 'Consent evidence is too long' using errcode = '22023';
  end if;

  if v_occurred_at > now() + interval '5 minutes' then
    raise exception 'Consent event time cannot be in the future' using errcode = '22023';
  end if;

  if p_event_type = 'revoked' and p_expires_at is not null then
    raise exception 'Revoked consent cannot have an expiry time' using errcode = '22023';
  end if;

  if p_event_type = 'granted' and p_expires_at is not null and p_expires_at <= v_occurred_at then
    raise exception 'Consent expiry must be after the grant time' using errcode = '22023';
  end if;

  select normalized_e164, validation_status, validation_reason
    into v_normalized, v_status, v_reason
  from public.normalize_phone_number(p_phone, 'PK')
  limit 1;

  if v_status <> 'valid' or v_normalized is null then
    raise exception 'A valid Pakistan mobile number is required: %', v_reason using errcode = '22023';
  end if;

  insert into public.contact_consent_events (
    organization_id, normalized_e164, event_type, source, evidence_note,
    evidence_reference, occurred_at, expires_at, recorded_by
  ) values (
    p_organization_id, v_normalized, p_event_type, p_source, v_note,
    v_reference, v_occurred_at, case when p_event_type = 'granted' then p_expires_at else null end, v_actor
  ) returning id into v_event_id;

  insert into public.audit_logs (
    organization_id, actor_user_id, action, target_type, target_id, metadata
  ) values (
    p_organization_id,
    v_actor,
    case when p_event_type = 'granted' then 'contacts.consent_granted' else 'contacts.consent_revoked' end,
    'contact_consent_event',
    v_event_id::text,
    jsonb_build_object(
      'normalizedE164', v_normalized,
      'source', p_source,
      'occurredAt', v_occurred_at,
      'expiresAt', case when p_event_type = 'granted' then p_expires_at else null end
    )
  );

  return v_event_id;
end;
$$;

create or replace function public.record_contact_suppression(
  p_organization_id uuid,
  p_phone text,
  p_event_type text,
  p_reason text default null,
  p_source text default 'manual',
  p_note text default null,
  p_occurred_at timestamptz default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_normalized text;
  v_status text;
  v_reason_text text;
  v_event_id bigint;
  v_occurred_at timestamptz := coalesce(p_occurred_at, now());
  v_note text := nullif(trim(coalesce(p_note, '')), '');
  v_latest_event text;
  v_latest_time timestamptz;
begin
  if v_actor is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if not public.can_manage_contact_compliance(p_organization_id) then
    raise exception 'Owner, Admin or Campaign Manager permission required to manage suppression' using errcode = '42501';
  end if;

  if p_event_type is null or p_event_type not in ('suppressed', 'lifted') then
    raise exception 'Suppression event type must be suppressed or lifted' using errcode = '22023';
  end if;

  if p_event_type = 'lifted' and not public.can_lift_contact_suppressions(p_organization_id) then
    raise exception 'Only Owner or Admin can lift a suppression' using errcode = '42501';
  end if;

  if p_source is null or p_source not in ('recipient_reply', 'import', 'api', 'manual', 'other') then
    raise exception 'Unsupported suppression source' using errcode = '22023';
  end if;

  if p_event_type = 'suppressed' and (p_reason is null or p_reason not in ('opt_out', 'complaint', 'manual', 'regulatory', 'other')) then
    raise exception 'A valid suppression reason is required' using errcode = '22023';
  end if;

  if p_event_type = 'lifted' and (p_reason is not null or v_note is null) then
    raise exception 'Lifting suppression requires a note and no suppression reason' using errcode = '22023';
  end if;

  if char_length(coalesce(v_note, '')) > 1000 then
    raise exception 'Suppression note is too long' using errcode = '22023';
  end if;

  if v_occurred_at > now() + interval '5 minutes' then
    raise exception 'Suppression event time cannot be in the future' using errcode = '22023';
  end if;

  select normalized_e164, validation_status, validation_reason
    into v_normalized, v_status, v_reason_text
  from public.normalize_phone_number(p_phone, 'PK')
  limit 1;

  if v_status <> 'valid' or v_normalized is null then
    raise exception 'A valid Pakistan mobile number is required: %', v_reason_text using errcode = '22023';
  end if;

  select e.event_type, e.occurred_at
    into v_latest_event, v_latest_time
  from public.contact_suppression_events e
  where e.organization_id = p_organization_id
    and e.normalized_e164 = v_normalized
  order by e.occurred_at desc, e.id desc
  limit 1;

  if p_event_type = 'suppressed' and v_latest_event = 'suppressed' then
    raise exception 'This number is already suppressed' using errcode = '22023';
  end if;

  if p_event_type = 'lifted' and v_latest_event is distinct from 'suppressed' then
    raise exception 'This number is not currently suppressed' using errcode = '22023';
  end if;

  if v_latest_time is not null and v_occurred_at < v_latest_time then
    raise exception 'Suppression state changes cannot be backdated before the current state event' using errcode = '22023';
  end if;

  insert into public.contact_suppression_events (
    organization_id, normalized_e164, event_type, reason, source, note, occurred_at, recorded_by
  ) values (
    p_organization_id,
    v_normalized,
    p_event_type,
    case when p_event_type = 'suppressed' then p_reason else null end,
    p_source,
    v_note,
    v_occurred_at,
    v_actor
  ) returning id into v_event_id;

  insert into public.audit_logs (
    organization_id, actor_user_id, action, target_type, target_id, metadata
  ) values (
    p_organization_id,
    v_actor,
    case when p_event_type = 'suppressed' then 'contacts.suppressed' else 'contacts.suppression_lifted' end,
    'contact_suppression_event',
    v_event_id::text,
    jsonb_build_object(
      'normalizedE164', v_normalized,
      'reason', case when p_event_type = 'suppressed' then p_reason else null end,
      'source', p_source,
      'occurredAt', v_occurred_at
    )
  );

  return v_event_id;
end;
$$;

create or replace function public.get_contact_compliance_status(
  p_organization_id uuid,
  p_phone text
)
returns table(
  normalized_e164 text,
  consent_state text,
  consent_event_id bigint,
  consent_source text,
  consent_occurred_at timestamptz,
  consent_expires_at timestamptz,
  suppression_state text,
  suppression_event_id bigint,
  suppression_reason text,
  suppression_source text,
  suppression_occurred_at timestamptz,
  eligibility_state text,
  block_reason text
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_normalized text;
  v_status text;
  v_reason text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if not public.is_org_member(p_organization_id) then
    raise exception 'Organization membership required' using errcode = '42501';
  end if;

  select n.normalized_e164, n.validation_status, n.validation_reason
    into v_normalized, v_status, v_reason
  from public.normalize_phone_number(p_phone, 'PK') n
  limit 1;

  if v_status <> 'valid' or v_normalized is null then
    raise exception 'A valid Pakistan mobile number is required: %', v_reason using errcode = '22023';
  end if;

  return query
  select * from public.contact_compliance_state_internal(p_organization_id, v_normalized);
end;
$$;

create or replace function public.list_contact_compliance_statuses(
  p_organization_id uuid,
  p_limit integer default 100
)
returns table(
  normalized_e164 text,
  consent_state text,
  consent_event_id bigint,
  consent_source text,
  consent_occurred_at timestamptz,
  consent_expires_at timestamptz,
  suppression_state text,
  suppression_event_id bigint,
  suppression_reason text,
  suppression_source text,
  suppression_occurred_at timestamptz,
  eligibility_state text,
  block_reason text
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if not public.is_org_member(p_organization_id) then
    raise exception 'Organization membership required' using errcode = '42501';
  end if;

  if p_limit is null or p_limit < 1 or p_limit > 500 then
    raise exception 'Limit must be between 1 and 500' using errcode = '22023';
  end if;

  return query
  with phones as (
    select e.normalized_e164, max(e.created_at) as last_recorded_at
    from public.contact_consent_events e
    where e.organization_id = p_organization_id
    group by e.normalized_e164
    union
    select e.normalized_e164, max(e.created_at) as last_recorded_at
    from public.contact_suppression_events e
    where e.organization_id = p_organization_id
    group by e.normalized_e164
  ), ranked as (
    select p.normalized_e164, max(p.last_recorded_at) as last_recorded_at
    from phones p
    group by p.normalized_e164
    order by max(p.last_recorded_at) desc, p.normalized_e164
    limit p_limit
  )
  select s.*
  from ranked r
  cross join lateral public.contact_compliance_state_internal(p_organization_id, r.normalized_e164) s
  order by r.last_recorded_at desc, r.normalized_e164;
end;
$$;

create or replace function public.list_contact_compliance_history(
  p_organization_id uuid,
  p_phone text
)
returns table(
  event_kind text,
  event_id bigint,
  event_type text,
  source text,
  reason text,
  detail text,
  evidence_reference text,
  occurred_at timestamptz,
  expires_at timestamptz,
  recorded_by uuid,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_normalized text;
  v_status text;
  v_reason text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if not public.can_manage_contact_compliance(p_organization_id) then
    raise exception 'Owner, Admin or Campaign Manager permission required to inspect compliance evidence' using errcode = '42501';
  end if;

  select n.normalized_e164, n.validation_status, n.validation_reason
    into v_normalized, v_status, v_reason
  from public.normalize_phone_number(p_phone, 'PK') n
  limit 1;

  if v_status <> 'valid' or v_normalized is null then
    raise exception 'A valid Pakistan mobile number is required: %', v_reason using errcode = '22023';
  end if;

  return query
  select *
  from (
    select
      'consent'::text as event_kind,
      c.id as event_id,
      c.event_type,
      c.source,
      null::text as reason,
      c.evidence_note as detail,
      c.evidence_reference,
      c.occurred_at,
      c.expires_at,
      c.recorded_by,
      c.created_at
    from public.contact_consent_events c
    where c.organization_id = p_organization_id and c.normalized_e164 = v_normalized

    union all

    select
      'suppression'::text,
      s.id,
      s.event_type,
      s.source,
      s.reason,
      s.note,
      null::text,
      s.occurred_at,
      null::timestamptz,
      s.recorded_by,
      s.created_at
    from public.contact_suppression_events s
    where s.organization_id = p_organization_id and s.normalized_e164 = v_normalized
  ) events
  order by events.occurred_at desc, events.created_at desc, events.event_id desc;
end;
$$;

create table if not exists public.recipient_eligibility_snapshots (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  recipient_preview_id uuid not null references public.recipient_previews(id) on delete cascade,
  created_by uuid references public.profiles(id) on delete set null,
  revision integer not null check (revision > 0),
  policy_version text not null default 'consent-suppression-v1' check (policy_version = 'consent-suppression-v1'),
  candidate_rows integer not null default 0 check (candidate_rows >= 0),
  eligible_rows integer not null default 0 check (eligible_rows >= 0),
  no_consent_rows integer not null default 0 check (no_consent_rows >= 0),
  consent_revoked_rows integer not null default 0 check (consent_revoked_rows >= 0),
  consent_expired_rows integer not null default 0 check (consent_expired_rows >= 0),
  suppressed_rows integer not null default 0 check (suppressed_rows >= 0),
  created_at timestamptz not null default now(),
  unique (recipient_preview_id, revision),
  check (candidate_rows = eligible_rows + no_consent_rows + consent_revoked_rows + consent_expired_rows + suppressed_rows)
);

create index if not exists recipient_eligibility_snapshots_org_created_idx
  on public.recipient_eligibility_snapshots (organization_id, created_at desc);

create index if not exists recipient_eligibility_snapshots_preview_revision_idx
  on public.recipient_eligibility_snapshots (recipient_preview_id, revision desc);

create table if not exists public.recipient_eligibility_rows (
  id bigint generated by default as identity primary key,
  snapshot_id uuid not null references public.recipient_eligibility_snapshots(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  recipient_preview_id uuid not null references public.recipient_previews(id) on delete cascade,
  preview_row_id bigint not null references public.recipient_preview_rows(id) on delete cascade,
  source_row_number integer not null check (source_row_number >= 2),
  display_name text,
  normalized_e164 text not null check (normalized_e164 ~ '^\+923[0-9]{9}$'),
  eligibility_state text not null check (eligibility_state in ('eligible', 'blocked')),
  block_reason text check (block_reason in ('no_consent', 'consent_revoked', 'consent_expired', 'suppressed')),
  consent_state text not null check (consent_state in ('none', 'granted', 'revoked', 'expired')),
  consent_event_id bigint references public.contact_consent_events(id) on delete set null,
  consent_source text,
  consent_occurred_at timestamptz,
  consent_expires_at timestamptz,
  suppression_state text not null check (suppression_state in ('clear', 'suppressed')),
  suppression_event_id bigint references public.contact_suppression_events(id) on delete set null,
  suppression_reason text,
  suppression_source text,
  suppression_occurred_at timestamptz,
  created_at timestamptz not null default now(),
  unique (snapshot_id, preview_row_id),
  check (
    (eligibility_state = 'eligible' and block_reason is null and consent_state = 'granted' and suppression_state = 'clear')
    or
    (eligibility_state = 'blocked' and block_reason is not null)
  )
);

create index if not exists recipient_eligibility_rows_snapshot_idx
  on public.recipient_eligibility_rows (snapshot_id, source_row_number);

create index if not exists recipient_eligibility_rows_org_phone_idx
  on public.recipient_eligibility_rows (organization_id, normalized_e164);

alter table public.recipient_eligibility_snapshots enable row level security;
alter table public.recipient_eligibility_rows enable row level security;

create policy "recipient_eligibility_snapshots_select_members"
on public.recipient_eligibility_snapshots
for select
to authenticated
using (public.is_org_member(organization_id));

create policy "recipient_eligibility_rows_select_members"
on public.recipient_eligibility_rows
for select
to authenticated
using (public.is_org_member(organization_id));

create or replace function public.list_recipient_eligibility_rows(
  p_organization_id uuid,
  p_preview_id uuid
)
returns table(
  preview_row_id bigint,
  source_row_number integer,
  display_name text,
  normalized_e164 text,
  source_filename text,
  preview_revision integer,
  consent_state text,
  consent_event_id bigint,
  consent_source text,
  consent_occurred_at timestamptz,
  consent_expires_at timestamptz,
  suppression_state text,
  suppression_event_id bigint,
  suppression_reason text,
  suppression_source text,
  suppression_occurred_at timestamptz,
  eligibility_state text,
  block_reason text
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if not public.is_org_member(p_organization_id) then
    raise exception 'Organization membership required' using errcode = '42501';
  end if;

  if not exists (
    select 1 from public.recipient_previews p
    where p.id = p_preview_id and p.organization_id = p_organization_id
  ) then
    raise exception 'Recipient preview not found' using errcode = 'P0002';
  end if;

  return query
  select
    r.id,
    r.source_row_number,
    r.display_name,
    r.normalized_e164,
    i.source_filename,
    p.revision,
    s.consent_state,
    s.consent_event_id,
    s.consent_source,
    s.consent_occurred_at,
    s.consent_expires_at,
    s.suppression_state,
    s.suppression_event_id,
    s.suppression_reason,
    s.suppression_source,
    s.suppression_occurred_at,
    s.eligibility_state,
    s.block_reason
  from public.recipient_preview_rows r
  join public.recipient_previews p on p.id = r.preview_id
  join public.contact_imports i on i.id = p.import_id
  cross join lateral public.contact_compliance_state_internal(p_organization_id, r.normalized_e164) s
  where r.organization_id = p_organization_id
    and r.preview_id = p_preview_id
    and r.decision = 'included'
  order by r.source_row_number, r.id;
end;
$$;

create or replace function public.create_recipient_eligibility_snapshot(
  p_organization_id uuid,
  p_preview_id uuid
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_snapshot_id uuid;
  v_revision integer;
  v_candidates integer;
  v_eligible integer;
  v_no_consent integer;
  v_revoked integer;
  v_expired integer;
  v_suppressed integer;
begin
  if v_actor is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if not public.can_manage_contact_compliance(p_organization_id) then
    raise exception 'Owner, Admin or Campaign Manager permission required to create eligibility snapshots' using errcode = '42501';
  end if;

  perform 1
  from public.recipient_previews p
  where p.id = p_preview_id
    and p.organization_id = p_organization_id
  for update;

  if not found then
    raise exception 'Recipient preview not found' using errcode = 'P0002';
  end if;

  if not exists (
    select 1 from public.recipient_preview_rows r
    where r.preview_id = p_preview_id
      and r.organization_id = p_organization_id
      and r.decision = 'included'
  ) then
    raise exception 'Recipient preview has no included candidates' using errcode = '22023';
  end if;

  select coalesce(max(s.revision), 0) + 1
    into v_revision
  from public.recipient_eligibility_snapshots s
  where s.recipient_preview_id = p_preview_id;

  insert into public.recipient_eligibility_snapshots (
    organization_id, recipient_preview_id, created_by, revision
  ) values (
    p_organization_id, p_preview_id, v_actor, v_revision
  ) returning id into v_snapshot_id;

  insert into public.recipient_eligibility_rows (
    snapshot_id, organization_id, recipient_preview_id, preview_row_id,
    source_row_number, display_name, normalized_e164, eligibility_state, block_reason,
    consent_state, consent_event_id, consent_source, consent_occurred_at, consent_expires_at,
    suppression_state, suppression_event_id, suppression_reason, suppression_source, suppression_occurred_at
  )
  select
    v_snapshot_id,
    p_organization_id,
    p_preview_id,
    r.id,
    r.source_row_number,
    r.display_name,
    r.normalized_e164,
    s.eligibility_state,
    s.block_reason,
    s.consent_state,
    s.consent_event_id,
    s.consent_source,
    s.consent_occurred_at,
    s.consent_expires_at,
    s.suppression_state,
    s.suppression_event_id,
    s.suppression_reason,
    s.suppression_source,
    s.suppression_occurred_at
  from public.recipient_preview_rows r
  cross join lateral public.contact_compliance_state_internal(p_organization_id, r.normalized_e164) s
  where r.preview_id = p_preview_id
    and r.organization_id = p_organization_id
    and r.decision = 'included'
  order by r.source_row_number, r.id;

  select
    count(*)::integer,
    count(*) filter (where eligibility_state = 'eligible')::integer,
    count(*) filter (where block_reason = 'no_consent')::integer,
    count(*) filter (where block_reason = 'consent_revoked')::integer,
    count(*) filter (where block_reason = 'consent_expired')::integer,
    count(*) filter (where block_reason = 'suppressed')::integer
  into v_candidates, v_eligible, v_no_consent, v_revoked, v_expired, v_suppressed
  from public.recipient_eligibility_rows r
  where r.snapshot_id = v_snapshot_id;

  update public.recipient_eligibility_snapshots
  set candidate_rows = v_candidates,
      eligible_rows = v_eligible,
      no_consent_rows = v_no_consent,
      consent_revoked_rows = v_revoked,
      consent_expired_rows = v_expired,
      suppressed_rows = v_suppressed
  where id = v_snapshot_id;

  insert into public.audit_logs (
    organization_id, actor_user_id, action, target_type, target_id, metadata
  ) values (
    p_organization_id,
    v_actor,
    'contacts.eligibility_snapshot_created',
    'recipient_eligibility_snapshot',
    v_snapshot_id::text,
    jsonb_build_object(
      'recipientPreviewId', p_preview_id,
      'revision', v_revision,
      'candidateRows', v_candidates,
      'eligibleRows', v_eligible,
      'noConsentRows', v_no_consent,
      'consentRevokedRows', v_revoked,
      'consentExpiredRows', v_expired,
      'suppressedRows', v_suppressed,
      'policyVersion', 'consent-suppression-v1'
    )
  );

  return v_snapshot_id;
end;
$$;

create or replace function public.list_recipient_eligibility_snapshots(
  p_organization_id uuid,
  p_preview_id uuid default null
)
returns table(
  snapshot_id uuid,
  recipient_preview_id uuid,
  revision integer,
  policy_version text,
  candidate_rows integer,
  eligible_rows integer,
  no_consent_rows integer,
  consent_revoked_rows integer,
  consent_expired_rows integer,
  suppressed_rows integer,
  created_at timestamptz,
  created_by uuid
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if not public.is_org_member(p_organization_id) then
    raise exception 'Organization membership required' using errcode = '42501';
  end if;

  return query
  select
    s.id,
    s.recipient_preview_id,
    s.revision,
    s.policy_version,
    s.candidate_rows,
    s.eligible_rows,
    s.no_consent_rows,
    s.consent_revoked_rows,
    s.consent_expired_rows,
    s.suppressed_rows,
    s.created_at,
    s.created_by
  from public.recipient_eligibility_snapshots s
  where s.organization_id = p_organization_id
    and (p_preview_id is null or s.recipient_preview_id = p_preview_id)
  order by s.created_at desc, s.revision desc
  limit 100;
end;
$$;

create or replace function public.get_recipient_eligibility_snapshot_rows(
  p_organization_id uuid,
  p_snapshot_id uuid
)
returns table(
  eligibility_row_id bigint,
  preview_row_id bigint,
  source_row_number integer,
  display_name text,
  normalized_e164 text,
  eligibility_state text,
  block_reason text,
  consent_state text,
  consent_source text,
  consent_occurred_at timestamptz,
  consent_expires_at timestamptz,
  suppression_state text,
  suppression_reason text,
  suppression_source text,
  suppression_occurred_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if not public.is_org_member(p_organization_id) then
    raise exception 'Organization membership required' using errcode = '42501';
  end if;

  if not exists (
    select 1 from public.recipient_eligibility_snapshots s
    where s.id = p_snapshot_id and s.organization_id = p_organization_id
  ) then
    raise exception 'Eligibility snapshot not found' using errcode = 'P0002';
  end if;

  return query
  select
    r.id,
    r.preview_row_id,
    r.source_row_number,
    r.display_name,
    r.normalized_e164,
    r.eligibility_state,
    r.block_reason,
    r.consent_state,
    r.consent_source,
    r.consent_occurred_at,
    r.consent_expires_at,
    r.suppression_state,
    r.suppression_reason,
    r.suppression_source,
    r.suppression_occurred_at
  from public.recipient_eligibility_rows r
  where r.snapshot_id = p_snapshot_id
    and r.organization_id = p_organization_id
  order by r.source_row_number, r.id;
end;
$$;

revoke all on public.contact_consent_events from public, anon, authenticated;
revoke all on public.contact_suppression_events from public, anon, authenticated;
revoke all on public.recipient_eligibility_snapshots from public, anon, authenticated;
revoke all on public.recipient_eligibility_rows from public, anon, authenticated;

grant select on public.recipient_eligibility_snapshots to authenticated;
grant select on public.recipient_eligibility_rows to authenticated;

grant all on public.contact_consent_events to service_role;
grant all on public.contact_suppression_events to service_role;
grant all on public.recipient_eligibility_snapshots to service_role;
grant all on public.recipient_eligibility_rows to service_role;

revoke all on function public.can_manage_contact_compliance(uuid) from public, anon;
revoke all on function public.can_lift_contact_suppressions(uuid) from public, anon;
revoke all on function public.contact_compliance_state_internal(uuid, text) from public, anon, authenticated;
revoke all on function public.record_contact_consent(uuid, text, text, text, text, text, timestamptz, timestamptz) from public, anon;
revoke all on function public.record_contact_suppression(uuid, text, text, text, text, text, timestamptz) from public, anon;
revoke all on function public.get_contact_compliance_status(uuid, text) from public, anon;
revoke all on function public.list_contact_compliance_statuses(uuid, integer) from public, anon;
revoke all on function public.list_contact_compliance_history(uuid, text) from public, anon;
revoke all on function public.list_recipient_eligibility_rows(uuid, uuid) from public, anon;
revoke all on function public.create_recipient_eligibility_snapshot(uuid, uuid) from public, anon;
revoke all on function public.list_recipient_eligibility_snapshots(uuid, uuid) from public, anon;
revoke all on function public.get_recipient_eligibility_snapshot_rows(uuid, uuid) from public, anon;

grant execute on function public.can_manage_contact_compliance(uuid) to authenticated, service_role;
grant execute on function public.can_lift_contact_suppressions(uuid) to authenticated, service_role;
grant execute on function public.contact_compliance_state_internal(uuid, text) to service_role;
grant execute on function public.record_contact_consent(uuid, text, text, text, text, text, timestamptz, timestamptz) to authenticated, service_role;
grant execute on function public.record_contact_suppression(uuid, text, text, text, text, text, timestamptz) to authenticated, service_role;
grant execute on function public.get_contact_compliance_status(uuid, text) to authenticated, service_role;
grant execute on function public.list_contact_compliance_statuses(uuid, integer) to authenticated, service_role;
grant execute on function public.list_contact_compliance_history(uuid, text) to authenticated, service_role;
grant execute on function public.list_recipient_eligibility_rows(uuid, uuid) to authenticated, service_role;
grant execute on function public.create_recipient_eligibility_snapshot(uuid, uuid) to authenticated, service_role;
grant execute on function public.list_recipient_eligibility_snapshots(uuid, uuid) to authenticated, service_role;
grant execute on function public.get_recipient_eligibility_snapshot_rows(uuid, uuid) to authenticated, service_role;

insert into public.app_meta (key, value)
values (
  'schema',
  jsonb_build_object(
    'version', '0.11.0',
    'phase', 'consent_suppression',
    'default_country', 'PK',
    'number_type', 'mobile',
    'normalization_version', 'pk-mobile-v1',
    'recipient_validation_version', 'recipient-validation-v1',
    'consent_suppression_policy_version', 'consent-suppression-v1',
    'consent_required_for_eligibility', true,
    'suppression_overrides_consent', true,
    'campaign_send_enabled', false
  )
)
on conflict (key) do update
set value = excluded.value,
    updated_at = now();

commit;
