begin;

-- BulkText Web 0.10.0 — Recipient Validation & Preview
-- Converts staged import rows into explicit, server-authoritative recipient preview snapshots.
-- Consent/suppression and campaign confirmation remain later gates.

create or replace function public.can_build_recipient_previews(p_organization_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.org_role(p_organization_id) in ('owner', 'admin', 'campaign_manager'), false);
$$;

create table if not exists public.recipient_previews (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  import_id uuid not null references public.contact_imports(id) on delete cascade,
  created_by uuid not null references public.profiles(id) on delete restrict,
  revision integer not null check (revision > 0),
  validation_version text not null default 'recipient-validation-v1' check (validation_version = 'recipient-validation-v1'),
  phone_normalization_version text not null default 'pk-mobile-v1' check (phone_normalization_version = 'pk-mobile-v1'),
  total_rows integer not null check (total_rows > 0),
  included_rows integer not null default 0 check (included_rows >= 0),
  invalid_phone_rows integer not null default 0 check (invalid_phone_rows >= 0),
  duplicate_rows integer not null default 0 check (duplicate_rows >= 0),
  manually_excluded_rows integer not null default 0 check (manually_excluded_rows >= 0),
  created_at timestamptz not null default now(),
  unique (import_id, revision),
  check (total_rows = included_rows + invalid_phone_rows + duplicate_rows + manually_excluded_rows)
);

create index if not exists recipient_previews_org_created_idx
  on public.recipient_previews (organization_id, created_at desc);

create index if not exists recipient_previews_import_revision_idx
  on public.recipient_previews (import_id, revision desc);

create table if not exists public.recipient_preview_rows (
  id bigint generated by default as identity primary key,
  preview_id uuid not null references public.recipient_previews(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  import_id uuid not null references public.contact_imports(id) on delete cascade,
  import_row_id bigint not null references public.contact_import_rows(id) on delete cascade,
  source_row_number integer not null check (source_row_number >= 2),
  raw_data jsonb not null check (jsonb_typeof(raw_data) = 'object'),
  raw_phone text not null default '',
  normalized_e164 text,
  phone_validation_status text not null check (phone_validation_status in (
    'valid', 'empty', 'invalid_characters', 'invalid_length', 'unsupported_country', 'unsupported_number_type'
  )),
  phone_validation_reason text not null,
  first_name text,
  last_name text,
  display_name text,
  custom_fields jsonb not null default '{}'::jsonb check (jsonb_typeof(custom_fields) = 'object'),
  duplicate_group_size integer not null default 0 check (duplicate_group_size >= 0),
  decision text not null check (decision in ('included', 'excluded')),
  exclusion_reason text check (exclusion_reason in ('invalid_phone', 'duplicate_in_file', 'manually_excluded')),
  created_at timestamptz not null default now(),
  unique (preview_id, import_row_id),
  check (normalized_e164 is null or normalized_e164 ~ '^\+923[0-9]{9}$'),
  check (
    (decision = 'included' and exclusion_reason is null and phone_validation_status = 'valid' and normalized_e164 is not null)
    or
    (decision = 'excluded' and exclusion_reason is not null)
  )
);

create index if not exists recipient_preview_rows_preview_idx
  on public.recipient_preview_rows (preview_id, source_row_number);

create index if not exists recipient_preview_rows_org_e164_idx
  on public.recipient_preview_rows (organization_id, normalized_e164)
  where normalized_e164 is not null;

create unique index if not exists recipient_preview_rows_unique_included_e164_idx
  on public.recipient_preview_rows (preview_id, normalized_e164)
  where decision = 'included' and normalized_e164 is not null;

alter table public.recipient_previews enable row level security;
alter table public.recipient_preview_rows enable row level security;

create policy "recipient_previews_select_members"
on public.recipient_previews
for select
to authenticated
using (public.is_org_member(organization_id));

create policy "recipient_preview_rows_select_members"
on public.recipient_preview_rows
for select
to authenticated
using (public.is_org_member(organization_id));

create or replace function public.list_contact_import_validation_rows(
  p_organization_id uuid,
  p_import_id uuid
)
returns table(
  import_row_id bigint,
  source_row_number integer,
  raw_phone text,
  normalized_e164 text,
  phone_validation_status text,
  phone_validation_reason text,
  first_name text,
  last_name text,
  display_name text,
  custom_fields jsonb,
  duplicate_group_size integer
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if not public.is_org_member(p_organization_id) then
    raise exception 'Organization membership required' using errcode = '42501';
  end if;

  if not exists (
    select 1 from public.contact_imports i
    where i.id = p_import_id and i.organization_id = p_organization_id
  ) then
    raise exception 'Import not found' using errcode = 'P0002';
  end if;

  return query
  with normalized as (
    select
      r.id,
      r.source_row_number,
      r.raw_phone,
      n.normalized_e164,
      n.validation_status,
      n.validation_reason,
      r.first_name,
      r.last_name,
      r.display_name,
      r.custom_fields
    from public.contact_import_rows r
    cross join lateral public.normalize_phone_number(r.raw_phone, 'PK') n
    where r.organization_id = p_organization_id
      and r.import_id = p_import_id
  ), ranked as (
    select
      n.*,
      case
        when n.validation_status = 'valid' and n.normalized_e164 is not null
          then count(*) over (partition by n.normalized_e164)::integer
        else 0
      end as group_size
    from normalized n
  )
  select
    r.id,
    r.source_row_number,
    r.raw_phone,
    r.normalized_e164,
    r.validation_status,
    r.validation_reason,
    r.first_name,
    r.last_name,
    r.display_name,
    r.custom_fields,
    r.group_size
  from ranked r
  order by r.source_row_number, r.id;
end;
$$;

create or replace function public.create_recipient_preview(
  p_organization_id uuid,
  p_import_id uuid,
  p_selected_row_ids bigint[]
)
returns uuid
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_actor uuid := auth.uid();
  v_preview_id uuid;
  v_total_rows integer;
  v_selected_count integer := coalesce(cardinality(p_selected_row_ids), 0);
  v_unique_selected integer;
  v_matching_valid integer;
  v_unique_numbers integer;
  v_revision integer;
  v_included integer;
  v_invalid integer;
  v_duplicate integer;
  v_manual integer;
begin
  if v_actor is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if not public.can_build_recipient_previews(p_organization_id) then
    raise exception 'Owner, Admin or Campaign Manager permission required to create recipient previews' using errcode = '42501';
  end if;

  select i.total_rows
    into v_total_rows
  from public.contact_imports i
  where i.id = p_import_id
    and i.organization_id = p_organization_id
  for update;

  if not found then
    raise exception 'Import not found' using errcode = 'P0002';
  end if;

  if v_selected_count < 1 then
    raise exception 'Select at least one valid recipient row' using errcode = '22023';
  end if;

  if array_position(p_selected_row_ids, null) is not null then
    raise exception 'Selected recipient row IDs cannot contain null values' using errcode = '22023';
  end if;

  select count(distinct selected_id)::integer
    into v_unique_selected
  from unnest(p_selected_row_ids) as selected(selected_id);

  if v_unique_selected <> v_selected_count then
    raise exception 'Selected recipient row IDs must be unique' using errcode = '22023';
  end if;

  select count(*)::integer, count(distinct n.normalized_e164)::integer
    into v_matching_valid, v_unique_numbers
  from public.contact_import_rows r
  cross join lateral public.normalize_phone_number(r.raw_phone, 'PK') n
  where r.organization_id = p_organization_id
    and r.import_id = p_import_id
    and r.id = any(p_selected_row_ids)
    and n.validation_status = 'valid'
    and n.normalized_e164 is not null;

  if v_matching_valid <> v_selected_count then
    raise exception 'Every selected row must belong to this import and contain a currently valid Pakistan mobile number' using errcode = '22023';
  end if;

  if v_unique_numbers <> v_selected_count then
    raise exception 'Only one selected row is allowed for each canonical phone number' using errcode = '22023';
  end if;

  select coalesce(max(p.revision), 0) + 1
    into v_revision
  from public.recipient_previews p
  where p.import_id = p_import_id;

  insert into public.recipient_previews (
    organization_id, import_id, created_by, revision, total_rows,
    included_rows, invalid_phone_rows, duplicate_rows, manually_excluded_rows
  ) values (
    p_organization_id, p_import_id, v_actor, v_revision, v_total_rows,
    0, 0, 0, v_total_rows
  ) returning id into v_preview_id;

  with normalized as (
    select
      r.*,
      n.normalized_e164 as current_e164,
      n.validation_status as current_status,
      n.validation_reason as current_reason
    from public.contact_import_rows r
    cross join lateral public.normalize_phone_number(r.raw_phone, 'PK') n
    where r.organization_id = p_organization_id
      and r.import_id = p_import_id
  ), grouped as (
    select
      n.*,
      case
        when n.current_status = 'valid' and n.current_e164 is not null
          then count(*) over (partition by n.current_e164)::integer
        else 0
      end as group_size
    from normalized n
  ), selected_numbers as (
    select g.current_e164
    from grouped g
    where g.id = any(p_selected_row_ids)
  )
  insert into public.recipient_preview_rows (
    preview_id, organization_id, import_id, import_row_id, source_row_number,
    raw_data, raw_phone, normalized_e164, phone_validation_status, phone_validation_reason,
    first_name, last_name, display_name, custom_fields, duplicate_group_size,
    decision, exclusion_reason
  )
  select
    v_preview_id,
    p_organization_id,
    p_import_id,
    g.id,
    g.source_row_number,
    g.raw_data,
    g.raw_phone,
    g.current_e164,
    g.current_status,
    g.current_reason,
    g.first_name,
    g.last_name,
    g.display_name,
    g.custom_fields,
    g.group_size,
    case
      when g.current_status = 'valid' and g.current_e164 is not null and g.id = any(p_selected_row_ids)
        then 'included'
      else 'excluded'
    end,
    case
      when g.current_status <> 'valid' or g.current_e164 is null then 'invalid_phone'
      when g.id = any(p_selected_row_ids) then null
      when exists (select 1 from selected_numbers s where s.current_e164 = g.current_e164) then 'duplicate_in_file'
      else 'manually_excluded'
    end
  from grouped g
  order by g.source_row_number, g.id;

  select
    count(*) filter (where decision = 'included')::integer,
    count(*) filter (where exclusion_reason = 'invalid_phone')::integer,
    count(*) filter (where exclusion_reason = 'duplicate_in_file')::integer,
    count(*) filter (where exclusion_reason = 'manually_excluded')::integer
  into v_included, v_invalid, v_duplicate, v_manual
  from public.recipient_preview_rows r
  where r.preview_id = v_preview_id;

  update public.recipient_previews
  set included_rows = v_included,
      invalid_phone_rows = v_invalid,
      duplicate_rows = v_duplicate,
      manually_excluded_rows = v_manual
  where id = v_preview_id;

  insert into public.audit_logs (
    organization_id, actor_user_id, action, target_type, target_id, metadata
  ) values (
    p_organization_id,
    v_actor,
    'contacts.recipient_preview_created',
    'recipient_preview',
    v_preview_id::text,
    jsonb_build_object(
      'importId', p_import_id,
      'revision', v_revision,
      'includedRows', v_included,
      'invalidPhoneRows', v_invalid,
      'duplicateRows', v_duplicate,
      'manuallyExcludedRows', v_manual,
      'validationVersion', 'recipient-validation-v1'
    )
  );

  return v_preview_id;
end;
$$;

create or replace function public.delete_contact_import(
  p_organization_id uuid,
  p_import_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_filename text;
begin
  if v_actor is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if not public.can_stage_contact_imports(p_organization_id) then
    raise exception 'Owner, Admin or Campaign Manager permission required to delete staged imports' using errcode = '42501';
  end if;

  select source_filename into v_filename
  from public.contact_imports
  where id = p_import_id and organization_id = p_organization_id;

  if v_filename is null then
    raise exception 'Import not found' using errcode = 'P0002';
  end if;

  if exists (
    select 1 from public.recipient_previews p
    where p.import_id = p_import_id and p.organization_id = p_organization_id
  ) then
    raise exception 'Import has recipient preview history and cannot be deleted' using errcode = '23503';
  end if;

  delete from public.contact_imports
  where id = p_import_id and organization_id = p_organization_id;

  insert into public.audit_logs (
    organization_id, actor_user_id, action, target_type, target_id, metadata
  ) values (
    p_organization_id,
    v_actor,
    'contacts.import_deleted',
    'contact_import',
    p_import_id::text,
    jsonb_build_object('filename', v_filename)
  );
end;
$$;

create or replace function public.list_recipient_previews(
  p_organization_id uuid,
  p_import_id uuid default null
)
returns table(
  preview_id uuid,
  import_id uuid,
  source_filename text,
  revision integer,
  validation_version text,
  total_rows integer,
  included_rows integer,
  invalid_phone_rows integer,
  duplicate_rows integer,
  manually_excluded_rows integer,
  created_at timestamptz,
  created_by uuid
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if not public.is_org_member(p_organization_id) then
    raise exception 'Organization membership required' using errcode = '42501';
  end if;

  return query
  select
    p.id,
    p.import_id,
    i.source_filename,
    p.revision,
    p.validation_version,
    p.total_rows,
    p.included_rows,
    p.invalid_phone_rows,
    p.duplicate_rows,
    p.manually_excluded_rows,
    p.created_at,
    p.created_by
  from public.recipient_previews p
  join public.contact_imports i on i.id = p.import_id
  where p.organization_id = p_organization_id
    and (p_import_id is null or p.import_id = p_import_id)
  order by p.created_at desc, p.revision desc
  limit 100;
end;
$$;

create or replace function public.get_recipient_preview_rows(
  p_organization_id uuid,
  p_preview_id uuid
)
returns table(
  preview_row_id bigint,
  import_row_id bigint,
  source_row_number integer,
  display_name text,
  raw_phone text,
  normalized_e164 text,
  phone_validation_status text,
  phone_validation_reason text,
  duplicate_group_size integer,
  decision text,
  exclusion_reason text,
  custom_fields jsonb
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if not public.is_org_member(p_organization_id) then
    raise exception 'Organization membership required' using errcode = '42501';
  end if;

  if not exists (
    select 1 from public.recipient_previews p
    where p.id = p_preview_id and p.organization_id = p_organization_id
  ) then
    raise exception 'Recipient preview not found' using errcode = 'P0002';
  end if;

  return query
  select
    r.id,
    r.import_row_id,
    r.source_row_number,
    r.display_name,
    r.raw_phone,
    r.normalized_e164,
    r.phone_validation_status,
    r.phone_validation_reason,
    r.duplicate_group_size,
    r.decision,
    r.exclusion_reason,
    r.custom_fields
  from public.recipient_preview_rows r
  where r.preview_id = p_preview_id
    and r.organization_id = p_organization_id
  order by r.source_row_number, r.id;
end;
$$;

revoke all on public.recipient_previews from public, anon, authenticated;
revoke all on public.recipient_preview_rows from public, anon, authenticated;
grant select on public.recipient_previews to authenticated;
grant select on public.recipient_preview_rows to authenticated;
grant all on public.recipient_previews to service_role;
grant all on public.recipient_preview_rows to service_role;

revoke all on function public.can_build_recipient_previews(uuid) from public, anon;
revoke all on function public.list_contact_import_validation_rows(uuid, uuid) from public, anon;
revoke all on function public.create_recipient_preview(uuid, uuid, bigint[]) from public, anon;
revoke all on function public.list_recipient_previews(uuid, uuid) from public, anon;
revoke all on function public.get_recipient_preview_rows(uuid, uuid) from public, anon;

grant execute on function public.can_build_recipient_previews(uuid) to authenticated, service_role;
grant execute on function public.list_contact_import_validation_rows(uuid, uuid) to authenticated, service_role;
grant execute on function public.create_recipient_preview(uuid, uuid, bigint[]) to authenticated, service_role;
grant execute on function public.list_recipient_previews(uuid, uuid) to authenticated, service_role;
grant execute on function public.get_recipient_preview_rows(uuid, uuid) to authenticated, service_role;

insert into public.app_meta (key, value)
values (
  'schema',
  jsonb_build_object(
    'version', '0.10.0',
    'phase', 'recipient_validation_preview',
    'default_country', 'PK',
    'number_type', 'mobile',
    'normalization_version', 'pk-mobile-v1',
    'recipient_validation_version', 'recipient-validation-v1',
    'consent_suppression_applied', false
  )
)
on conflict (key) do update
set value = excluded.value,
    updated_at = now();

commit;
