begin;
create or replace function public.can_confirm_campaign(p_organization_id uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.can_manage_org(p_organization_id); $$;

create or replace function public.render_message_template_internal(p_template text,p_display_name text,p_first_name text,p_last_name text,p_phone text,p_custom_fields jsonb)
returns text language plpgsql immutable set search_path=public as $$
declare v_text text:=coalesce(p_template,''); v_match text[]; v_full text; v_token text; v_key text; v_value text; v_json jsonb;
begin
 perform public.validate_message_template_internal(v_text);
 for v_match in select regexp_matches(v_text,'(\{\{[[:space:]]*([^{}]+)[[:space:]]*\}\})','g') loop
  v_full:=v_match[1]; v_token:=trim(v_match[2]); if left(v_token,7)='custom:' then v_token:='custom:'||trim(substr(v_token,8)); end if; v_value:=null;
  if v_token='name' then v_value:=nullif(trim(coalesce(p_display_name,'')),''); if v_value is null then v_value:=nullif(trim(concat_ws(' ',nullif(trim(coalesce(p_first_name,'')),''),nullif(trim(coalesce(p_last_name,'')),''))),''); end if;
  elsif v_token='first_name' then v_value:=nullif(trim(coalesce(p_first_name,'')),'');
  elsif v_token='last_name' then v_value:=nullif(trim(coalesce(p_last_name,'')),'');
  elsif v_token='phone' then v_value:=nullif(trim(coalesce(p_phone,'')),'');
  elsif left(v_token,7)='custom:' then v_key:=substr(v_token,8); v_json:=coalesce(p_custom_fields,'{}'::jsonb)->v_key; if v_json is not null and jsonb_typeof(v_json)<>'null' then if jsonb_typeof(v_json)='string' then v_value:=nullif(trim(v_json#>>'{}'),''); else v_value:=nullif(v_json::text,''); if v_value in ('{}','[]') then v_value:=null; end if; end if; end if;
  end if;
  if v_value is null then raise exception 'Recipient is missing personalization value for token: %',v_token using errcode='22023'; end if;
  v_text:=replace(v_text,v_full,v_value);
 end loop;
 if position('{{' in v_text)>0 or position('}}' in v_text)>0 then raise exception 'Rendered message still contains an unresolved personalization token' using errcode='22023'; end if;
 return v_text;
end; $$;

create or replace function public.sms_segment_estimate_internal(p_text text)
returns table(sms_encoding text,character_count integer,encoding_units integer,segment_count integer)
language plpgsql immutable set search_path=public as $$
declare v_text text:=coalesce(p_text,''); v_basic constant text:='@£$¥èéùìòÇ'||chr(10)||'Øø'||chr(13)||'ÅåΔ_ΦΓΛΩΠΨΣΘΞÆæßÉ !"#¤%&''()*+,-./0123456789:;<=>?¡ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÑÜ§¿abcdefghijklmnopqrstuvwxyzäöñüà'; v_extension constant text:='^{}'||chr(92)||'[~]|€'||chr(12); v_char text; v_gsm_units integer:=0; v_unicode_units integer:=0; v_is_gsm boolean:=true; v_i integer;
begin
 character_count:=char_length(v_text); if character_count=0 then sms_encoding:='GSM-7'; encoding_units:=0; segment_count:=0; return next; return; end if;
 for v_i in 1..character_count loop v_char:=substr(v_text,v_i,1); if strpos(v_basic,v_char)>0 then v_gsm_units:=v_gsm_units+1; elsif strpos(v_extension,v_char)>0 then v_gsm_units:=v_gsm_units+2; else v_is_gsm:=false; end if; v_unicode_units:=v_unicode_units+case when octet_length(convert_to(v_char,'UTF8'))=4 then 2 else 1 end; end loop;
 if v_is_gsm then sms_encoding:='GSM-7'; encoding_units:=v_gsm_units; segment_count:=case when v_gsm_units<=160 then 1 else (v_gsm_units+152)/153 end; else sms_encoding:='Unicode'; encoding_units:=v_unicode_units; segment_count:=case when v_unicode_units<=70 then 1 else (v_unicode_units+66)/67 end; end if; return next;
end; $$;

create table if not exists public.campaigns(
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
 source_draft_id uuid references public.message_composer_drafts(id) on delete set null, source_draft_updated_at timestamptz not null,
 source_eligibility_snapshot_id uuid references public.recipient_eligibility_snapshots(id) on delete set null, source_recipient_preview_id uuid references public.recipient_previews(id) on delete set null,
 title text not null, message_template_snapshot text not null, template_syntax_version text not null, template_variables text[] not null default array[]::text[], eligibility_policy_version text not null,
 sms_segment_model_version text not null default 'gsm7-ucs2-v1', recipient_count integer not null default 0 check(recipient_count>=0), estimated_sms_units integer not null default 0 check(estimated_sms_units>=0),
 gsm7_recipients integer not null default 0 check(gsm7_recipients>=0), unicode_recipients integer not null default 0 check(unicode_recipients>=0), minimum_segments integer not null default 0 check(minimum_segments>=0), maximum_segments integer not null default 0 check(maximum_segments>=0), average_segments numeric(12,4) not null default 0 check(average_segments>=0),
 gateway_device_id_snapshot uuid not null, gateway_device_name text not null, gateway_manufacturer text, gateway_model text, gateway_last_seen_at timestamptz, gateway_last_inventory_at timestamptz,
 gateway_sim_id_snapshot uuid not null, sim_subscription_id integer not null check(sim_subscription_id>=0), sim_slot_index integer not null check(sim_slot_index between 0 and 7), sim_carrier_name text, sim_display_name text, sim_identity_hash text,
 recipient_limit_snapshot integer not null default 5000 check(recipient_limit_snapshot>0), confirmed_by uuid references public.profiles(id) on delete set null, confirmed_at timestamptz not null default now(), created_at timestamptz not null default now(),
 check(char_length(trim(title)) between 1 and 120), check(recipient_count=gsm7_recipients+unicode_recipients), check(sim_identity_hash is null or sim_identity_hash~'^[0-9a-f]{64}$')
);
create unique index if not exists campaigns_confirmation_idempotency_idx on public.campaigns(organization_id,source_draft_id,source_draft_updated_at,gateway_device_id_snapshot,gateway_sim_id_snapshot) where source_draft_id is not null;
create index if not exists campaigns_org_confirmed_idx on public.campaigns(organization_id,confirmed_at desc);

create table if not exists public.campaign_recipients(
 id bigint generated by default as identity primary key, campaign_id uuid not null references public.campaigns(id) on delete cascade, organization_id uuid not null references public.organizations(id) on delete cascade,
 source_eligibility_row_id bigint, source_preview_row_id bigint, source_row_number integer not null check(source_row_number>=2), display_name text, normalized_e164 text not null check(normalized_e164~'^\+923[0-9]{9}$'),
 rendered_message text not null, sms_encoding text not null check(sms_encoding in('GSM-7','Unicode')), character_count integer not null check(character_count>0), encoding_units integer not null check(encoding_units>0), segment_count integer not null check(segment_count>0),
 eligibility_state text not null default 'eligible' check(eligibility_state='eligible'), consent_state text not null check(consent_state='granted'), consent_event_id bigint, consent_source text, consent_occurred_at timestamptz, consent_expires_at timestamptz,
 suppression_state text not null check(suppression_state='clear'), suppression_event_id bigint, suppression_reason text, suppression_source text, suppression_occurred_at timestamptz, created_at timestamptz not null default now(),
 unique(campaign_id,normalized_e164), unique(campaign_id,source_eligibility_row_id), check(char_length(rendered_message) between 1 and 16000)
);
create index if not exists campaign_recipients_campaign_idx on public.campaign_recipients(campaign_id,source_row_number,id);
alter table public.campaigns enable row level security; alter table public.campaign_recipients enable row level security;
create policy "campaigns_select_owner" on public.campaigns for select to authenticated using(public.is_org_member(organization_id));
create policy "campaign_recipients_select_owner" on public.campaign_recipients for select to authenticated using(public.is_org_member(organization_id));

create or replace function public.confirm_campaign(p_organization_id uuid,p_draft_id uuid,p_device_id uuid) returns uuid language plpgsql security definer set search_path=public,extensions as $$
declare v_actor uuid:=auth.uid(); v_draft public.message_composer_drafts%rowtype; v_snapshot public.recipient_eligibility_snapshots%rowtype; v_preview_id uuid; v_device public.gateway_devices%rowtype; v_sim public.gateway_device_sims%rowtype; v_campaign_id uuid; v_existing_id uuid; v_row record; v_rendered text; v_encoding text; v_characters integer; v_units integer; v_segments integer; v_count integer:=0; v_total integer:=0; v_gsm integer:=0; v_unicode integer:=0; v_min integer:=null; v_max integer:=0;
begin
 if v_actor is null then raise exception 'Authentication required' using errcode='42501'; end if; if not public.can_confirm_campaign(p_organization_id) then raise exception 'Personal workspace owner permission required to confirm campaigns' using errcode='42501'; end if;
 select d.* into v_draft from public.message_composer_drafts d where d.id=p_draft_id and d.organization_id=p_organization_id for update; if v_draft.id is null then raise exception 'Message draft not found' using errcode='P0002'; end if;
 select s.* into v_snapshot from public.recipient_eligibility_snapshots s where s.id=v_draft.eligibility_snapshot_id and s.organization_id=p_organization_id; if v_snapshot.id is null or v_snapshot.eligible_rows<=0 then raise exception 'A valid eligibility snapshot with at least one eligible recipient is required' using errcode='22023'; end if; v_preview_id:=v_snapshot.recipient_preview_id;
 select d.* into v_device from public.gateway_devices d where d.id=p_device_id and d.organization_id=p_organization_id and d.status='active'; if v_device.id is null then raise exception 'An active paired Android phone is required' using errcode='22023'; end if;
 select s.* into v_sim from public.gateway_device_sim_bindings b join public.gateway_device_sims s on s.id=b.sim_id where b.device_id=v_device.id and s.device_id=v_device.id and s.present; if v_sim.id is null then raise exception 'The paired phone must have a currently present selected SIM before campaign confirmation' using errcode='22023'; end if;
 select c.id into v_existing_id from public.campaigns c where c.organization_id=p_organization_id and c.source_draft_id=v_draft.id and c.source_draft_updated_at=v_draft.updated_at and c.gateway_device_id_snapshot=v_device.id and c.gateway_sim_id_snapshot=v_sim.id limit 1; if v_existing_id is not null then return v_existing_id; end if;
 insert into public.campaigns(organization_id,source_draft_id,source_draft_updated_at,source_eligibility_snapshot_id,source_recipient_preview_id,title,message_template_snapshot,template_syntax_version,template_variables,eligibility_policy_version,gateway_device_id_snapshot,gateway_device_name,gateway_manufacturer,gateway_model,gateway_last_seen_at,gateway_last_inventory_at,gateway_sim_id_snapshot,sim_subscription_id,sim_slot_index,sim_carrier_name,sim_display_name,sim_identity_hash,confirmed_by)
 values(p_organization_id,v_draft.id,v_draft.updated_at,v_snapshot.id,v_preview_id,v_draft.title,v_draft.message_template,v_draft.syntax_version,v_draft.template_variables,v_snapshot.policy_version,v_device.id,v_device.display_name,v_device.manufacturer,v_device.model,v_device.last_seen_at,v_device.last_inventory_at,v_sim.id,v_sim.subscription_id,v_sim.slot_index,v_sim.carrier_name,v_sim.display_name,v_sim.sim_identity_hash,v_actor) returning id into v_campaign_id;
 for v_row in select e.id eligibility_row_id,e.preview_row_id,e.source_row_number,e.display_name,e.normalized_e164,e.consent_state,e.consent_event_id,e.consent_source,e.consent_occurred_at,e.consent_expires_at,e.suppression_state,e.suppression_event_id,e.suppression_reason,e.suppression_source,e.suppression_occurred_at,p.first_name,p.last_name,p.custom_fields from public.recipient_eligibility_rows e join public.recipient_preview_rows p on p.id=e.preview_row_id where e.organization_id=p_organization_id and e.snapshot_id=v_snapshot.id and e.eligibility_state='eligible' order by e.source_row_number,e.id loop
  v_rendered:=public.render_message_template_internal(v_draft.message_template,v_row.display_name,v_row.first_name,v_row.last_name,v_row.normalized_e164,v_row.custom_fields);
  select s.sms_encoding,s.character_count,s.encoding_units,s.segment_count into v_encoding,v_characters,v_units,v_segments from public.sms_segment_estimate_internal(v_rendered) s; if v_segments<=0 then raise exception 'Rendered message is empty for recipient %',v_row.normalized_e164 using errcode='22023'; end if;
  insert into public.campaign_recipients(campaign_id,organization_id,source_eligibility_row_id,source_preview_row_id,source_row_number,display_name,normalized_e164,rendered_message,sms_encoding,character_count,encoding_units,segment_count,consent_state,consent_event_id,consent_source,consent_occurred_at,consent_expires_at,suppression_state,suppression_event_id,suppression_reason,suppression_source,suppression_occurred_at)
  values(v_campaign_id,p_organization_id,v_row.eligibility_row_id,v_row.preview_row_id,v_row.source_row_number,v_row.display_name,v_row.normalized_e164,v_rendered,v_encoding,v_characters,v_units,v_segments,v_row.consent_state,v_row.consent_event_id,v_row.consent_source,v_row.consent_occurred_at,v_row.consent_expires_at,v_row.suppression_state,v_row.suppression_event_id,v_row.suppression_reason,v_row.suppression_source,v_row.suppression_occurred_at);
  v_count:=v_count+1; v_total:=v_total+v_segments; if v_encoding='GSM-7' then v_gsm:=v_gsm+1; else v_unicode:=v_unicode+1; end if; v_min:=case when v_min is null then v_segments else least(v_min,v_segments) end; v_max:=greatest(v_max,v_segments);
 end loop;
 if v_count<>v_snapshot.eligible_rows then raise exception 'Eligibility snapshot changed unexpectedly while confirming campaign' using errcode='40001'; end if;
 update public.campaigns c set recipient_count=v_count,estimated_sms_units=v_total,gsm7_recipients=v_gsm,unicode_recipients=v_unicode,minimum_segments=coalesce(v_min,0),maximum_segments=v_max,average_segments=case when v_count=0 then 0 else round(v_total::numeric/v_count::numeric,4) end where c.id=v_campaign_id;
 insert into public.audit_logs(organization_id,actor_user_id,action,target_type,target_id,metadata) values(p_organization_id,v_actor,'campaign.confirmed','campaign',v_campaign_id::text,jsonb_build_object('sourceDraftId',v_draft.id,'eligibilitySnapshotId',v_snapshot.id,'recipientCount',v_count,'estimatedSmsUnits',v_total,'gatewayDeviceId',v_device.id,'gatewaySimId',v_sim.id,'subscriptionId',v_sim.subscription_id,'segmentModelVersion','gsm7-ucs2-v1'));
 return v_campaign_id;
end; $$;

create or replace function public.list_campaign_confirmations(p_organization_id uuid) returns table(campaign_id uuid,title text,recipient_count integer,estimated_sms_units integer,encoding_summary text,minimum_segments integer,maximum_segments integer,gateway_device_name text,sim_carrier_name text,sim_slot_index integer,confirmed_at timestamptz) language plpgsql stable security definer set search_path=public as $$ begin if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if; if not public.is_org_member(p_organization_id) then raise exception 'Personal workspace access required' using errcode='42501'; end if; return query select c.id,c.title,c.recipient_count,c.estimated_sms_units,case when c.recipient_count=0 then '—' when c.gsm7_recipients=c.recipient_count then 'GSM-7' when c.unicode_recipients=c.recipient_count then 'Unicode' else 'Mixed' end,c.minimum_segments,c.maximum_segments,c.gateway_device_name,c.sim_carrier_name,c.sim_slot_index,c.confirmed_at from public.campaigns c where c.organization_id=p_organization_id order by c.confirmed_at desc,c.id desc limit 100; end; $$;

create or replace function public.get_campaign_confirmation(p_organization_id uuid,p_campaign_id uuid) returns table(campaign_id uuid,title text,source_draft_id uuid,source_draft_updated_at timestamptz,source_eligibility_snapshot_id uuid,message_template_snapshot text,template_syntax_version text,eligibility_policy_version text,sms_segment_model_version text,recipient_count integer,estimated_sms_units integer,gsm7_recipients integer,unicode_recipients integer,minimum_segments integer,maximum_segments integer,average_segments numeric,gateway_device_id uuid,gateway_device_name text,gateway_manufacturer text,gateway_model text,gateway_last_seen_at timestamptz,gateway_last_inventory_at timestamptz,gateway_sim_id uuid,sim_subscription_id integer,sim_slot_index integer,sim_carrier_name text,sim_display_name text,confirmed_at timestamptz) language plpgsql stable security definer set search_path=public as $$ begin if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if; if not public.is_org_member(p_organization_id) then raise exception 'Personal workspace access required' using errcode='42501'; end if; return query select c.id,c.title,c.source_draft_id,c.source_draft_updated_at,c.source_eligibility_snapshot_id,c.message_template_snapshot,c.template_syntax_version,c.eligibility_policy_version,c.sms_segment_model_version,c.recipient_count,c.estimated_sms_units,c.gsm7_recipients,c.unicode_recipients,c.minimum_segments,c.maximum_segments,c.average_segments,c.gateway_device_id_snapshot,c.gateway_device_name,c.gateway_manufacturer,c.gateway_model,c.gateway_last_seen_at,c.gateway_last_inventory_at,c.gateway_sim_id_snapshot,c.sim_subscription_id,c.sim_slot_index,c.sim_carrier_name,c.sim_display_name,c.confirmed_at from public.campaigns c where c.organization_id=p_organization_id and c.id=p_campaign_id; end; $$;

create or replace function public.list_campaign_confirmation_recipients(p_organization_id uuid,p_campaign_id uuid,p_limit integer default 100,p_offset integer default 0) returns table(recipient_id bigint,source_row_number integer,display_name text,normalized_e164 text,rendered_message text,sms_encoding text,character_count integer,encoding_units integer,segment_count integer,consent_state text,consent_source text,consent_occurred_at timestamptz,consent_expires_at timestamptz,suppression_state text) language plpgsql stable security definer set search_path=public as $$ begin if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if; if not public.is_org_member(p_organization_id) then raise exception 'Personal workspace access required' using errcode='42501'; end if; if p_limit<1 or p_limit>500 then raise exception 'Recipient page size must be between 1 and 500' using errcode='22023'; end if; if p_offset<0 then raise exception 'Recipient offset cannot be negative' using errcode='22023'; end if; if not exists(select 1 from public.campaigns c where c.id=p_campaign_id and c.organization_id=p_organization_id) then raise exception 'Campaign not found' using errcode='P0002'; end if; return query select r.id,r.source_row_number,r.display_name,r.normalized_e164,r.rendered_message,r.sms_encoding,r.character_count,r.encoding_units,r.segment_count,r.consent_state,r.consent_source,r.consent_occurred_at,r.consent_expires_at,r.suppression_state from public.campaign_recipients r where r.organization_id=p_organization_id and r.campaign_id=p_campaign_id order by r.source_row_number,r.id limit p_limit offset p_offset; end; $$;

revoke all on public.campaigns from public,anon,authenticated; revoke all on public.campaign_recipients from public,anon,authenticated; grant select on public.campaigns to authenticated; grant select on public.campaign_recipients to authenticated; grant all on public.campaigns to service_role; grant all on public.campaign_recipients to service_role;
revoke all on function public.can_confirm_campaign(uuid) from public,anon; revoke all on function public.render_message_template_internal(text,text,text,text,text,jsonb) from public,anon,authenticated; revoke all on function public.sms_segment_estimate_internal(text) from public,anon,authenticated; revoke all on function public.confirm_campaign(uuid,uuid,uuid) from public,anon; revoke all on function public.list_campaign_confirmations(uuid) from public,anon; revoke all on function public.get_campaign_confirmation(uuid,uuid) from public,anon; revoke all on function public.list_campaign_confirmation_recipients(uuid,uuid,integer,integer) from public,anon;
grant execute on function public.can_confirm_campaign(uuid) to authenticated,service_role; grant execute on function public.render_message_template_internal(text,text,text,text,text,jsonb) to service_role; grant execute on function public.sms_segment_estimate_internal(text) to service_role; grant execute on function public.confirm_campaign(uuid,uuid,uuid) to authenticated,service_role; grant execute on function public.list_campaign_confirmations(uuid) to authenticated,service_role; grant execute on function public.get_campaign_confirmation(uuid,uuid) to authenticated,service_role; grant execute on function public.list_campaign_confirmation_recipients(uuid,uuid,integer,integer) to authenticated,service_role;
update public.app_meta set value=coalesce(value,'{}'::jsonb)||jsonb_build_object('version','0.14.0','phase','campaign_confirmation_snapshot','campaign_confirmation_enabled',true,'campaign_confirmation_version','campaign-confirmation-v1','campaign_snapshot_immutable',true,'campaign_send_enabled',false,'queue_enabled',false),updated_at=now() where key='schema';
commit;
